export const countries = [
  { label: "Afghanistan", value: "+93" },
  { label: "Albania", value: "+355" },
  { label: "Algeria", value: "+213" },
  { label: "Andorra", value: "+376" },
  { label: "Angola", value: "+244" },
  { label: "Argentina", value: "+54" },
  { label: "Australia", value: "+61" },
  { label: "Austria", value: "+43" },
  { label: "Bangladesh", value: "+880" },
  { label: "Belgium", value: "+32" },
  { label: "Brazil", value: "+55" },
  { label: "Canada", value: "+1" },
  { label: "China", value: "+86" },
  { label: "Denmark", value: "+45" },
  { label: "Egypt", value: "+20" },
  { label: "France", value: "+33" },
  { label: "Germany", value: "+49" },
  { label: "India", value: "+91" },
  { label: "Indonesia", value: "+62" },
  { label: "Italy", value: "+39" },
  { label: "Japan", value: "+81" },
  { label: "Mexico", value: "+52" },
  { label: "Netherlands", value: "+31" },
  { label: "Nigeria", value: "+234" },
  { label: "Pakistan", value: "+92" },
  { label: "Philippines", value: "+63" },
  { label: "Russia", value: "+7" },
  { label: "Saudi Arabia", value: "+966" },
  { label: "South Africa", value: "+27" },
  { label: "Spain", value: "+34" },
  { label: "Sri Lanka", value: "+94" },
  { label: "Sweden", value: "+46" },
  { label: "Thailand", value: "+66" },
  { label: "United Arab Emirates", value: "+971" },
  { label: "United Kingdom", value: "+44" },
  { label: "United States", value: "+1" },
  { label: "Vietnam", value: "+84" }
];